package com.example.springboot.domain;

import java.io.Serializable;
import java.util.Date;

public class InputItem implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_zhxq_inputitem.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_zhxq_inputitem.item_name
     *
     * @mbg.generated
     */
    private String itemName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_zhxq_inputitem.db_key
     *
     * @mbg.generated
     */
    private String dbKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_zhxq_inputitem.is_cascade
     *
     * @mbg.generated
     */
    private Integer isCascade;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_zhxq_inputitem.create_user
     *
     * @mbg.generated
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_zhxq_inputitem.school_id
     *
     * @mbg.generated
     */
    private Integer schoolId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_zhxq_inputitem.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_zhxq_inputitem.datas
     *
     * @mbg.generated
     */
    private String datas;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_zhxq_inputitem
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_zhxq_inputitem.id
     *
     * @return the value of t_zhxq_inputitem.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_zhxq_inputitem.id
     *
     * @param id the value for t_zhxq_inputitem.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_zhxq_inputitem.item_name
     *
     * @return the value of t_zhxq_inputitem.item_name
     *
     * @mbg.generated
     */
    public String getItemName() {
        return itemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_zhxq_inputitem.item_name
     *
     * @param itemName the value for t_zhxq_inputitem.item_name
     *
     * @mbg.generated
     */
    public void setItemName(String itemName) {
        this.itemName = itemName == null ? null : itemName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_zhxq_inputitem.db_key
     *
     * @return the value of t_zhxq_inputitem.db_key
     *
     * @mbg.generated
     */
    public String getDbKey() {
        return dbKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_zhxq_inputitem.db_key
     *
     * @param dbKey the value for t_zhxq_inputitem.db_key
     *
     * @mbg.generated
     */
    public void setDbKey(String dbKey) {
        this.dbKey = dbKey == null ? null : dbKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_zhxq_inputitem.is_cascade
     *
     * @return the value of t_zhxq_inputitem.is_cascade
     *
     * @mbg.generated
     */
    public Integer getIsCascade() {
        return isCascade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_zhxq_inputitem.is_cascade
     *
     * @param isCascade the value for t_zhxq_inputitem.is_cascade
     *
     * @mbg.generated
     */
    public void setIsCascade(Integer isCascade) {
        this.isCascade = isCascade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_zhxq_inputitem.create_user
     *
     * @return the value of t_zhxq_inputitem.create_user
     *
     * @mbg.generated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_zhxq_inputitem.create_user
     *
     * @param createUser the value for t_zhxq_inputitem.create_user
     *
     * @mbg.generated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_zhxq_inputitem.school_id
     *
     * @return the value of t_zhxq_inputitem.school_id
     *
     * @mbg.generated
     */
    public Integer getSchoolId() {
        return schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_zhxq_inputitem.school_id
     *
     * @param schoolId the value for t_zhxq_inputitem.school_id
     *
     * @mbg.generated
     */
    public void setSchoolId(Integer schoolId) {
        this.schoolId = schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_zhxq_inputitem.update_time
     *
     * @return the value of t_zhxq_inputitem.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_zhxq_inputitem.update_time
     *
     * @param updateTime the value for t_zhxq_inputitem.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_zhxq_inputitem.datas
     *
     * @return the value of t_zhxq_inputitem.datas
     *
     * @mbg.generated
     */
    public String getDatas() {
        return datas;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_zhxq_inputitem.datas
     *
     * @param datas the value for t_zhxq_inputitem.datas
     *
     * @mbg.generated
     */
    public void setDatas(String datas) {
        this.datas = datas == null ? null : datas.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zhxq_inputitem
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", itemName=").append(itemName);
        sb.append(", dbKey=").append(dbKey);
        sb.append(", isCascade=").append(isCascade);
        sb.append(", createUser=").append(createUser);
        sb.append(", schoolId=").append(schoolId);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", datas=").append(datas);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}