package com.example.springboot.dao;

import com.example.springboot.domain.InputItem;
import com.example.springboot.domain.InputItemExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface InputItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zhxq_inputitem
     *
     * @mbg.generated
     */
    long countByExample(InputItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zhxq_inputitem
     *
     * @mbg.generated
     */
    int deleteByExample(InputItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zhxq_inputitem
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zhxq_inputitem
     *
     * @mbg.generated
     */
    int insert(InputItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zhxq_inputitem
     *
     * @mbg.generated
     */
    int insertSelective(InputItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zhxq_inputitem
     *
     * @mbg.generated
     */
    List<InputItem> selectByExampleWithBLOBs(InputItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zhxq_inputitem
     *
     * @mbg.generated
     */
    List<InputItem> selectByExample(InputItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zhxq_inputitem
     *
     * @mbg.generated
     */
    InputItem selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zhxq_inputitem
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") InputItem record, @Param("example") InputItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zhxq_inputitem
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") InputItem record, @Param("example") InputItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zhxq_inputitem
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") InputItem record, @Param("example") InputItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zhxq_inputitem
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(InputItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zhxq_inputitem
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(InputItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zhxq_inputitem
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(InputItem record);
}